name: Helm Deployer
description: Opens pull request against a given flux managed clusters repo modifying the specified clusters
inputs:
  repository:
    description: Flux repository to open PR against
    required: true
  cluster:
    description: Cluster to modify HelmRelease in
    required: true
  namespace:
    description: Namespace to modify HelmRelease in
    required: true
  file:
    description: File path in filesystem of HelmReleaseCRD (filename must match with filename in flux repository)
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      env:
        file_path: ${{ inputs.file }}
        repository: ${{ inputs.repository }}
        cluster: ${{ inputs.cluster }}
        namespace: ${{ inputs.namespace }}
      with:
        result-encoding: string
        retries: 3
        script: |

          const fs = require('fs')

          //Read file
          const file = fs.readFileSync(process.env.file_path, 'utf8');

          //Convert file to base64
          const bFile = btoa(file)

          //Get main branch sha
          const main_branch = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: process.env.repository,
              ref: 'heads/main',
          })

          //Create branch in flux repo
          console.log(main_branch)
          console.log(main_branch.data.object.sha)

          //Obtain file's blob sha in the branch

          //Modify file in this new branch


          //Open pull request