name: Helm Deployer
description: Opens pull request against a given flux managed clusters repo modifying the specified clusters
inputs:
  repository:
    description: Flux repository to open PR against
    required: true
  cluster:
    description: Cluster to modify HelmRelease in
    required: true
  namespace:
    description: Namespace to modify HelmRelease in
    required: true
  file:
    description: File path in filesystem of HelmReleaseCRD (filename must match with filename in flux repository)
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      env:
        file_path: ${{ inputs.file }}
      with:
        result-encoding: string
        retries: 3
        script: |

          const fs = require('fs')
          
          const file = fs.readFileSync(process.env.file_path, 'utf8');
          const bFile = btoa(file)
          console.log(bFile)