apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: ever-project
      spec:
        values:
          global:
            ra:
              repository: acr.azurecr.io
    target:
      kind: HelmRelease